apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: trailing-slash
spec:
  enabled: true
  requires: ">=2.13.0"
  author:
    name: Halo
    website: https://github.com/halo-dev
  logo: logo.svg
  homepage: https://github.com/halo-sigs/plugin-trailing-slash#readme
  repo: https://github.com/halo-sigs/plugin-trailing-slash
  issues: https://github.com/halo-sigs/plugin-trailing-slash/issues
  displayName: "Trailing Slash"
  description: "重写请求去除尾部斜杠，以保证 URL 规范化, 例如: /path/ -> /path"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-sigs/plugin-trailing-slash/blob/main/LICENSE"
